version: 0.1
phases:
  install:
    commands:
        - apt-get update
        - apt-get install httpd -y
        - service httpd start
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
  discard-paths: yes
cache:
  paths: